name: Smoke tests
on:
  schedule:
  - cron:  '23 2 * * *'
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          install: npm install
          test_chrome: ./node_modules/.bin/cypress-tags run -e TAGS='@SmokeTest' --browser chrome
          test_edge: ./node_modules/.bin/cypress-tags run -e TAGS='@SmokeTest' --browser edge
          test_firefox: ./node_modules/.bin/cypress-tags run -e TAGS='@SmokeTest' --browser firefox
