name: Smoke tests
on:
  schedule:
  - cron:  '0 7 * * *'
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
              
      - name: Install dependencies
        run: npm install
        
      - name: Run smoke tests on chrome
        run: ./node_modules/.bin/cypress-tags run -e TAGS='@SmokeTest' --browser chrome
          
      - name: Run smoke tests on edge
        run: ./node_modules/.bin/cypress-tags run -e TAGS='@SmokeTest' --browser edge
          
      - name: Run smoke tests on firefox
        run: ./node_modules/.bin/cypress-tags run -e TAGS='@SmokeTest' --browser firefox
